services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mtaa
    ports:
      - "5434:5432"
    volumes:
      - postgres_db:/data/postgres
volumes:
  postgres_db:

